# Generated by Django 4.2.2 on 2023-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigoregistro',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
