# Generated by Django 4.2.2 on 2023-06-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_codigoregistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='codigoregistro',
            new_name='codregistro',
        ),
    ]
